[package]
name = "bungee-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
thiserror = "1.0"

[build-dependencies]
cc = "1.0"
bindgen = "0.69"
cmake = "0.1"

[lib]
name = "bungee_ffi"
crate-type = ["cdylib", "rlib"]
